### ISSUE TITLE
Text not wrapping properly on Android.

### ISSUE THREAD

**Issue by godofgrunts** [GDQuest/website#219] opened 2020-08-27 05:08 UTC
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

On Android (both on Firefox and Chrome), the text background color fits the phone screen, but the text extends past the background making it hard to read.

**What is the expected behavior?**

The text should wrap when it reaches the width of the screen.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Open https://www.gdquest.com/tutorial/godot/gdscript/optimization-engine/ on Android.
![Screenshot_20200826-182827](https://user-images.githubusercontent.com/338843/91386197-7ba0c800-e800-11ea-9f98-836d4ed90389.png)
![Screenshot_20200826-182831](https://user-images.githubusercontent.com/338843/91386240-8e1b0180-e800-11ea-8952-b85dc643b7be.png)

## Other ##

**Other information** 

This is on a Google Pixel XL.

**Comment by Calinou** [comment] 2020-11-05 19:03
I can't reproduce this on an OnePlus 6.

## Chromium 83

![Screenshot_20201105-195908](https://user-images.githubusercontent.com/180032/98284760-e4938180-1fa1-11eb-85b8-6406cc9ee51c.jpg)

## Firefox 82

![Screenshot_20201105-195935](https://user-images.githubusercontent.com/180032/98284783-ecebbc80-1fa1-11eb-815e-7bccc3b705ec.jpg)

**Comment by NathanLovato** [comment] 2020-11-05 19:52
This might be fixed already, I think there were two similar issues, I updated the CSS and it might have fixed this too. Gonna test and close the issue if I can't reproduce on the phone.

**Comment by NathanLovato** [comment] 2020-11-05 19:54
Can't reproduce anymore, closing for now. Thanks!

**Closed by NathanLovato** 2020-11-05 19:54 UTC
Labels: bug, good first issue
